import greenfoot.*;
import java.util.Collections;
import java.util.ArrayList;

/**
 * An overlay world that pauses the game and displays a 10-second math quiz.
 * (NOW WITH FULL DIFFICULTY LOGIC)
 */
public class QuizWorld extends World
{
    private GameWorld originWorld; 
    private Treasure treasure;     
    private int treasureValue;     
    private int correctAnswer;     
    private int difficultyLevel; // 0=Easy, 1=Medium, 2=Hard
    
    // --- NEW VARIABLE ---
    // We'll store the question string here, generated by the new methods
    private String questionString; 

    private SimpleTimer quizTimer = new SimpleTimer();
    private int quizTimeLeft = 10; 

    /**
     * Constructor (This should be the same as your current one)
     */
    public QuizWorld(GameWorld originalGameWorld, Treasure treasure, int difficulty)
    {    
        super(originalGameWorld.getWidth(), originalGameWorld.getHeight(), 1); 
        
        this.originWorld = originalGameWorld;
        this.treasure = treasure;
        this.treasureValue = treasure.getValue();
        this.difficultyLevel = difficulty; // Store the difficulty
        
        // Create the semi-transparent overlay
        GreenfootImage snapshot = new GreenfootImage(originalGameWorld.getBackground());
        GreenfootImage overlay = new GreenfootImage(getWidth(), getHeight());
        overlay.setColor(new greenfoot.Color(0, 0, 0, 150)); 
        overlay.fill();
        snapshot.drawImage(overlay, 0, 0);
        setBackground(snapshot);

        // Add the quiz UI on top
        prepareQuiz();
        
        // Start the 10-second timer
        quizTimer.mark();
        updateQuizTimerDisplay(); 
    }

    // --- THIS IS THE MODIFIED "ROUTER" METHOD ---
    /**
     * Prepares the quiz by calling the correct helper method
     * based on the difficulty level.
     */
    private void prepareQuiz()
    {
        // Use a switch to decide which question generator to use
        switch (difficultyLevel) {
            case 0: // Easy
                generateEasyQuestion();
                break;
            case 1: // Medium
                generateMediumQuestion();
                break;
            case 2: // Hard
                generateHardQuestion();
                break;
            default: // Failsafe, just do Easy
                generateEasyQuestion();
                break;
        }

        // --- This part is mostly the same as before ---
        
        // 3. Display the question
        GreenfootImage bg = getBackground();
        bg.setColor(greenfoot.Color.WHITE);
        bg.setFont(new Font("Arial", true, false, 36));
        // Use the new questionString variable
        bg.drawString(questionString, getWidth() / 2 - 100, getHeight() / 4); 

        // 4. Prepare answer values
        ArrayList<Integer> answers = new ArrayList<>();
        answers.add(correctAnswer);
        
        // Generate 3 random wrong answers
        // Make the range bigger for harder questions
        int answerRange = (difficultyLevel == 0) ? 21 : 101; // 0-20 for Easy, 0-100 for Med/Hard
        
        while (answers.size() < 4) {
            int wrongAnswer = Greenfoot.getRandomNumber(answerRange); 
            // Make sure wrong answer isn't the same or already in the list
            if (wrongAnswer != correctAnswer && !answers.contains(wrongAnswer)) {
                answers.add(wrongAnswer);
            }
        }
        Collections.shuffle(answers); // Randomize the order

        // 5. Add answer buttons
        int yPos = getHeight() / 2 + 50; 
        int xOffset = getWidth() / 5; 
        addObject(new AnswerButton(answers.get(0), answers.get(0) == correctAnswer), xOffset, yPos);
        addObject(new AnswerButton(answers.get(1), answers.get(1) == correctAnswer), xOffset * 2, yPos);
        addObject(new AnswerButton(answers.get(2), answers.get(2) == correctAnswer), xOffset * 3, yPos);
        addObject(new AnswerButton(answers.get(3), answers.get(3) == correctAnswer), xOffset * 4, yPos);
    }
    
    // --- NEW HELPER METHODS ---

    /**
     * Generates an Addition (+) or Subtraction (-) problem.
     * (Rubric: Easy)
     */
    private void generateEasyQuestion() {
        int num1 = Greenfoot.getRandomNumber(10) + 1; // 1-10
        int num2 = Greenfoot.getRandomNumber(10) + 1; // 1-10

        if (Greenfoot.getRandomNumber(2) == 0) {
            // Addition
            questionString = num1 + " + " + num2 + " = ?";
            correctAnswer = num1 + num2;
        } else {
            // Subtraction (no negatives)
            if (num1 < num2) { // Swap them
                int temp = num1;
                num1 = num2;
                num2 = temp;
            }
            questionString = num1 + " - " + num2 + " = ?";
            correctAnswer = num1 - num2;
        }
    }

    /**
     * Generates a Multiplication (*) or Division (/) problem.
     * (Rubric: Medium)
     */
    private void generateMediumQuestion() {
        if (Greenfoot.getRandomNumber(2) == 0) {
            // Multiplication
            int num1 = Greenfoot.getRandomNumber(9) + 2; // 2-10
            int num2 = Greenfoot.getRandomNumber(9) + 2; // 2-10
            questionString = num1 + " * " + num2 + " = ?";
            correctAnswer = num1 * num2;
        } else {
            // Division (guaranteed whole number)
            // We do this by generating the answer and divisor first
            int answer = Greenfoot.getRandomNumber(9) + 2; // 2-10
            int divisor = Greenfoot.getRandomNumber(9) + 2; // 2-10
            int dividend = answer * divisor; // This will be the big number
            
            questionString = dividend + " / " + divisor + " = ?";
            correctAnswer = answer;
        }
    }

    /**
     * Generates a mix of Addition (+) and Multiplication (*) problems.
     * (Rubric: Hard)
     */
    private void generateHardQuestion() {
        // Get a random number from 0 to 3
        // 0 = Add, 1 = Subtract, 2 = Multiply, 3 = Divide
        int operationType = Greenfoot.getRandomNumber(4); 
    
        if (operationType == 0) {
            // --- Penjumlahan (Addition) ---
            int num1 = Greenfoot.getRandomNumber(20) + 1; // 1-20
            int num2 = Greenfoot.getRandomNumber(20) + 1; // 1-20
            questionString = num1 + " + " + num2 + " = ?";
            correctAnswer = num1 + num2;
            
        } else if (operationType == 1) {
            // --- Pengurangan (Subtraction) ---
            int num1 = Greenfoot.getRandomNumber(20) + 1; // 1-20
            int num2 = Greenfoot.getRandomNumber(20) + 1; // 1-20
            
            // To prevent negative answers, make num1 the bigger number
            if (num1 < num2) { 
                int temp = num1;
                num1 = num2;
                num2 = temp;
            }
            questionString = num1 + " - " + num2 + " = ?";
            correctAnswer = num1 - num2;
            
        } else if (operationType == 2) {
            // --- Perkalian (Multiplication) ---
            int num1 = Greenfoot.getRandomNumber(11) + 2; // 2-12
            int num2 = Greenfoot.getRandomNumber(11) + 2; // 2-12
            questionString = num1 + " * " + num2 + " = ?";
            correctAnswer = num1 * num2;
            
        } else {
            // --- Pembagian (Division) ---
            // We create the answer first to guarantee a whole number
            int answer = Greenfoot.getRandomNumber(9) + 2; // 2-10
            int divisor = Greenfoot.getRandomNumber(9) + 2; // 2-10
            int dividend = answer * divisor; // The big number
            
            questionString = dividend + " / " + divisor + " = ?";
            correctAnswer = answer;
        }
    }

    // --- Your other methods (act, updateQuizTimerDisplay, checkAnswer) ---
    // --- remain unchanged and should be kept below this line. ---
    
    public void act() {
        if (quizTimer.hasElapsed(1000)) {
            if (quizTimeLeft > 0) {
                quizTimeLeft--;
                updateQuizTimerDisplay();
                quizTimer.mark();
                if (quizTimeLeft == 0) {
                    checkAnswer(false);
                }
            }
        }
    }
    
    private void updateQuizTimerDisplay() {
        GreenfootImage bg = getBackground();
        bg.setColor(new greenfoot.Color(0, 0, 0, 150)); 
        bg.fillRect(getWidth() / 2 - 50, 40, 150, 40); 
        bg.setColor(greenfoot.Color.WHITE);
        bg.setFont(new Font("Arial", true, false, 24));
        bg.drawString("Time: " + quizTimeLeft, getWidth() / 2 - 30, 70);
    }
    
    public void checkAnswer(boolean wasCorrect) 
    {
        quizTimeLeft = -1;
        GreenfootImage bg = getBackground();
        bg.setFont(new Font("Arial", true, false, 48));
        int coinsEarned = 0;
        
        if (wasCorrect) {
            bg.drawString("Correct! +" + treasureValue + " pts / +" + GameWorld.COIN_REWARD_TREASURE + "$", getWidth() / 2 - 200, getHeight() / 2 - 50);
            originWorld.addScore(treasureValue); 
            boolean levelComplete = originWorld.addKeyItem();
            originWorld.removeObject(this.treasure); 
            treasure.startCooldown();
            if (levelComplete) {
                return; 
            }
        } else {
            bg.drawString("Incorrect! -20s", getWidth() / 2 - 80, getHeight() / 2 - 50);
            originWorld.reduceTimer(20);
            treasure.startCooldown();
        }
        
        Greenfoot.delay(60);
        if (coinsEarned > 0) {
            originWorld.addCoins(coinsEarned);
        }
        Greenfoot.setWorld(originWorld);
        originWorld.onResumeFromPause(); 
    }
}
